[project]
name = "multicalibration"
version = "0.1.0"
description = "Code for AI-SQE paper 'Multicalibration for LLM-based Code Generation'"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=4.4.1",
    "matplotlib==3.10.3",
    "numpy==2.3.1",
    "pandas==2.3.1",
    "scikit-learn==1.6.1",
    "scipy==1.16.0",
    "tabulate==0.9.0",
    "termcolor==3.1.0",
]
